### ISSUE TITLE
[FEAT] change database implementation

### ISSUE THREAD

**Issue by kennethtegrado** [kennethtegrado/projectx#4]
Create a new implementation of database so we will get a more realistic approach for querying with the search function.

**Roadmap**
- [ ] create collection of delivery receipts inside data.ts at the data directory
- [ ] create util function that will processes pagination and querying
- [ ] change implementation of withFetchTableData
